site_name: CafeX Documentation
site_dir: site
theme:
  name: material

plugins:
- search:
    separator: '[\s]+'
    lang: en
#uncomment if you want to use the mkdocstrings plugin auto documentation generation
#- gen-files:
#    scripts:
#    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
    nav_title: Table of Contents
    nav_position: left
    nav_collapsible: true
    nav_mindepth: 2
- section-index
- mkdocstrings

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences